spring:
  application:
    name: transaction-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sar_assistant}
    username: ${SPRING_DATASOURCE_USERNAME:saruser}
    password: ${SPRING_DATASOURCE_PASSWORD:sarpass123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080